### ISSUE TITLE
Test CompositeRigidBodyMassMatrixCalculator with joints to ignore. 

### ISSUE THREAD

**Issue by SylvainBertrand** [ihmcrobotics/mecano#6]
The following exception when running Valkyrie simulation with a non-empty list of joints to ignore:
```
java.lang.NullPointerException
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:500)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator$CompositeRigidBodyInertia.computeMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:470)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator.updateMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:245)
	at us.ihmc.mecano.algorithms.CompositeRigidBodyMassMatrixCalculator.getMassMatrix(CompositeRigidBodyMassMatrixCalculator.java:290)
	at us.ihmc.commonWalkingControlModules.momentumBasedController.optimization.DynamicsMatrixCalculator.computeMatrices(DynamicsMatrixCalculator.java:110)
	at us.ihmc.commonWalkingControlModules.momentumBasedController.optimization.DynamicsMatrixCalculator.compute(DynamicsMatrixCalculator.java:91)
	at us.ihmc.commonWalkingControlModules.controllerCore.WholeBodyInverseDynamicsSolver.compute(WholeBodyInverseDynamicsSolver.java:187)
	at us.ihmc.commonWalkingControlModules.controllerCore.WholeBodyControllerCore.doInverseDynamics(WholeBodyControllerCore.java:257)
	at us.ihmc.commonWalkingControlModules.controllerCore.WholeBodyControllerCore.compute(WholeBodyControllerCore.java:221)
	at us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.highLevelStates.WalkingControllerState.doAction(WalkingControllerState.java:211)
	at us.ihmc.robotics.stateMachine.core.StateMachine.doAction(StateMachine.java:193)
	at us.ihmc.robotics.stateMachine.core.StateMachine.doActionAndTransition(StateMachine.java:170)
	at us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.HumanoidHighLevelControllerManager.doControl(HumanoidHighLevelControllerManager.java:156)
	at us.ihmc.robotics.robotController.ModularRobotController.doControl(ModularRobotController.java:22)
	at us.ihmc.avatar.AvatarControllerThread.run(AvatarControllerThread.java:285)
	at us.ihmc.avatar.ControllerTask.execute(ControllerTask.java:47)
	at us.ihmc.concurrent.runtime.barrierScheduler.implicitContext.Task.run(Task.java:161)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SylvainBertrand** [comment]
Fixed in version 0.2.1
